site_name: Automation Bible #by A.Brodziński & K.Więcek

site_url: https://automate.guru/

pages:
  - Home: 'azure-devops-audit-logs-forwarding.md'
  - Home: 'test.md'

theme:
  name: 'material'
  features:
    - tabs
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
      # text: 'Ubuntu'
      # code: 'Consolas'
      text: 'Roboto'
      # code: 'Roboto Mono'
      code: 'Ubuntu Mono'

nav:
    # - About: 'index.md'
    - 'Azure DevOps':
      - Audit Logs Forwarder: 'azure-devops-audit-logs-forwarding.md'
      - Multi-Stage YAML Pipeline Configuration: 'multi-stage-yaml-pipeline-configuration.md'
      - Universal ARM Template Deployment Script: 'universal-arm-deployment-script'

    - Azure Lighthouse Configuration: 'azure-lighthouse-configuration.md'
    - 'PowerShell':
      - Web-Based Automation With Selenium: 'powershell-web-browser-automation.md'
    
    - Copy Azure database between stages: 'copy-database-between-stages.md'
    - Automatic Certificate Generation for AKS: 'automatic-certificate-generation-aks.md'

    - 'Azure Management Group':
      - Hierarchy Best Practises: 'management-group-best-practises.md'
      - Deploy As a Code: 'deploy-management-group-hierarchy'
      
    - 'Azure Policy/ Compliance':
      - Fix MSI Role Assignment: 'fix-msi-role-assignment.md'
      - Security And Compliance As A Code - TDD: 'security-and-compliance-as-a-code-azure-policy-tdd.md'
      - Continous Inspection For Azure Policy: 'azure-policy-continous-integration.md'
      # - Automate Role Assignment For Policy Assignment Identity: 'ensure-policy-assignment-msi-permission-for-mg.md'
    # - ARM What-If Deployment PR Comment: 'arm-what-if-deployment-pull-request-comment.md'

    # - 'User Guide':
    #     - 'Writing your docs': 'writing-your-docs.md'
    #     - 'Styling your docs': 'styling-your-docs.md'
    
    # - Automated:
    #     - 'How long can tittle be???????asdhajdjkahkjahjdsajk': 'license.md'
    #     - 'Release Notes': 'release-notes.md'

    # - Worth to check: 'worth-to-check.md'

extra:
  disqus: 'automate-guru'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - pymdownx.tabbed

extra_javascript:
  - javascripts/extra.js

# google_analytics: ['UA-160963982-1', 'auto']
