site_name: Automation Bible #by A.Brodziński & K.Więcek

pages:
  - Home: 'azure-devops-audit-logs-forwarding.md'
  # - Home: 'test.md'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
      # text: 'Ubuntu'
      # code: 'Consolas'
      text: 'Roboto'
      # code: 'Roboto Mono'
      code: 'Ubuntu Mono'



nav:
    # - About: 'index.md'
    - Azure DevOps Audit Logs Forwarder: 'azure-devops-audit-logs-forwarding.md'
    - Azure Lighthouse configuration: 'azure-ligthouse-configuration.md'
    # - Azure Subscription With Selenium: 'powershell-selenium-azure-subscription'
    
    # - 'User Guide':
    #     - 'Writing your docs': 'writing-your-docs.md'
    #     - 'Styling your docs': 'styling-your-docs.md'
    
    # - Automated:
    #     - 'How long can tittle be???????asdhajdjkahkjahjdsajk': 'license.md'
    #     - 'Release Notes': 'release-notes.md'

    # - Worth to check: 'worth-to-check.md'

extra:
  disqus: 'automate-guru'

google_analytics: ['UA-160963982-1', 'auto']

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false